apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  kind: helm
  url: https://charts.kubegems.io/kubegems
  values:
    global:
      kubegemsVersion: v1.22.2
      # choose 'registry.cn-beijing.aliyuncs.com' or 'docker.io'
      imageRegistry: docker.io
      storageClass: local-path # change me to use a different storage class
    ingress:
      hostname: dashboard.kubegems.io # change me to use a production hostname
